# Generated by Django 6.0.7 on 2026-07-16 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('rating', models.FloatField(default=0)),
                ('hours', models.CharField(blank=True, help_text='e.g. Mon-Sun 11am-2am', max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('vibe', models.CharField(choices=[('casual', 'Casual'), ('rowdy', 'Rowdy'), ('family', 'Family-friendly')], default='casual', max_length=20)),
                ('team_tags', models.CharField(blank=True, max_length=300)),
                ('google_place_id', models.CharField(blank=True, max_length=120, null=True)),
                ('source', models.CharField(default='seed', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tags', to='core.bar')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tags', to='core.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bar', 'match', 'user')},
            },
        ),
    ]
